version: '3'

services: 
  myredis:
    restart: always
    image: 'redis:alpine'
  mypostgres:
    restart: always
    image: 'postgres:alpine'
    environment: 
      - POSTGRES_PASSWORD=1qaz2wsx
      - POSTGRES_DB=myappdb
      - POSTGRES_USER=myappuser
    volumes:
      - C:\Users\tomas\temp\postgresdata:/var/lib/postgresql/data
  mybackend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mybackend
    environment: 
        CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /opt/app/node_modules
      - C:\Users\tomas\temp\compose\mybackend:/opt/app
    environment: 
      - POSTGRES_PASSWORD=1qaz2wsx
      - POSTGRES_DB=myappdb
      - POSTGRES_USER=myappuser
      - REDIS_HOST=myredis
      - POSTGRES_HOST=mypostgres
    ports: 
      - "5000:4000"
  mynginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./mynginx
    ports: 
      - '9090:80'
  myfrontend:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./myfrontend
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /opt/app/node_modules
      - C:\Users\tomas\temp\compose\myfrontend:/opt/app